imgix/contentful

.gitignore, package-lock.json, package.json, src/components/ConfigScreen.spec.tsx, src/components/Dialog.tsx, src/components/Field.tsx
Adds an instance of `ImgixAPI` to the Dialog component, which will eventually be used to generate images queried from the imgix management API.
=> feat: create ImgixAPI instance with user-supplied API key

package-lock.json, package.json, src/components/Dialog.tsx
This PR incorporates type definitions from imgix-management-js into the Dialog component.
=> feat: import type definitions from imgix-management-js

package-lock.json, package.json, src/components/Dialog.spec.tsx, src/components/Dialog.tsx
This PR became an amalgamation of different tweaks and improvements to address previous feedback. I've kept them all in the same branch so as to avoid confusion with other feature work. Here's a summary of the changes:
- improve typings for `apiKey` mentioned in [this comment](https://github.com/imgix/contentful/pull/16#discussion_r607851568)
- replace instances of `let` with `const` mentioned in [this comment](https://github.com/imgix/contentful/pull/21#discussion_r614797263)
- make source and image path data parsing more DRY as mentioned in [this comment](https://github.com/imgix/contentful/pull/21#discussion_r614799999)
- extract imgix subdomains from source API response
- upgrade imgix-management-js to stable version
- emit better error messages from imgix-management-js
=> chore: make various improvements

src/components/ConfigScreen.css, src/components/ConfigScreen.tsx, src/components/Field.spec.tsx
https://user-images.githubusercontent.com/15919091/124035144-01594b00-d9b1-11eb-9dc0-5d56a8975325.mov
=> feat(config): make imgix dashboard link clickable

src/components/ConfigScreen.tsx, src/components/Dialog.tsx, src/components/Gallery.css, src/components/Gallery.tsx
Also addresses feedback left in #28
=> fix(dialog): return callback with `undefined` if no image chosen 

src/components/ConfigScreen.tsx
=> feat(config): obscure user's API key

src/components/Dialog.css, src/components/Gallery.css, src/components/Gallery.tsx
- Change grid template to allow for more flexible rows
- Change grid margins to fix right margin spacing
=> style: change grid row template and margins

src/components/Dialog.css, src/components/Dialog.tsx, src/components/Field.tsx
Note: the styling still needs to be tightened up, but going to save that for later
https://user-images.githubusercontent.com/15919091/125211058-7867cc80-e258-11eb-8df7-5f741e872777.mov
=> feat: add close button

src/components/Dialog.css, src/components/Gallery.css, src/components/Gallery.tsx, src/index.css
This PR changes some of the styles and makes the `Gallery` responsive. I followed the Figma design, but made some adjustments when the thumbnails were too large. For example, I made the grid 5 columns at 769px. This will need to be approved by design, but feel free to adjust what I've added.
I also moved the margin/padding from the individual components to the parent `Dialog` component. This makes it easier to manage and adjust vs. individual components.
https://user-images.githubusercontent.com/8587383/125365062-710ff400-e328-11eb-8d77-4b0ce6de7dfd.mov
https://user-images.githubusercontent.com/8587383/125365070-75d4a800-e328-11eb-95c0-972a837e425b.mov
=> Responsive updates

src/components/Dialog/Dialog.css, src/components/Dialog/Dialog.tsx, src/components/Dialog/DialogHeader.css, src/components/Dialog/DialogHeader.tsx, src/components/Dialog/index.ts, src/components/Pagination/Pagination.css, src/components/Pagination/Pagination.tsx, src/components/Pagination/index.ts, src/components/SourceSelect/SourceSelectDropdown.tsx, src/components/SourceSelect/index.ts
This PR refactors the dialog component to create 3 new components. This helps reduce and isolate state mutations and also splits the styles into their respective component directories.
=> feat: create header, select, and pagination components

src/components/Dialog/Dialog.tsx, src/components/Gallery/ImageGallery.tsx, src/components/Gallery/ImagePagination.tsx
This PR allows users to select a page of assets based on the list items available in the pagination dropdown menu.
https://user-images.githubusercontent.com/15919091/125862924-05aa67e5-cf9c-409f-8dac-d986ee6832ab.mov
=> feat(gallery): use current page index to query assets from imgix

src/components/Dialog/Dialog.css, src/components/Dialog/DialogHeader.css, src/components/Dialog/DialogHeader.tsx, src/components/Field/Field.tsx, src/components/Gallery/GridImage.css, src/components/Gallery/ImageGallery.css, src/components/Gallery/ImageGallery.tsx, src/components/Gallery/ImagePagination.css, src/components/Gallery/ImagePagination.tsx, src/components/ImageSelect/ImageSelect.css, src/components/ImageSelect/ImageSelect.tsx
This PR adds responsiveness through css styles and some `.tsx` refactoring.
Notes:
Contentful APP has a `min-width: 1024px` on the `.client` element which prevents us from styling our plug-in under 980px. This means that 980px is the "last chance" to style our plugin as it will remain in the same proportion throughout all other screen-widths.
- [Jira](https://imgix.atlassian.net/browse/PE-1112)
- [Design](https://www.figma.com/file/g8hMEYgG3KaQ8d3YDVJA4h/Contentful-Plug-In-Designs?node-id=169%3A1744)
=> style(gallery): [PE-1112] Responsiveness and styles

src/components/ConfigScreen/ConfigScreen.css, src/components/ConfigScreen/ConfigScreen.tsx
Adds requested changes from design review
- [Jira](https://imgix.atlassian.net/browse/PE-1169)
=> style: [PE-1169] Design Changes

src/components/SourceSelect/SourceSelect.css, src/components/SourceSelect/SourceSelectDropdown.tsx
=> style: adjusts dropdown width

LICENSE.md
Saw this was out of date so I thought I would change it
=> chore: update copyright

src/components/Gallery/ImagePagination.tsx
=> feat(gallery): disable pagination buttons if currently viewing the first or last page

src/components/Dialog/Dialog.tsx
=> fix: cast noSourcesError within catch block

src/components/ConfigScreen/ConfigScreen.css, src/components/ConfigScreen/ConfigScreen.tsx
This PR adds styles to match contentful feedback on config screen.
- [Jira](https://imgix.atlassian.net/browse/PE-1254)
- [Details](https://imgix.slack.com/archives/CAXNXSJHJ/p1628782247045200?thread_ts=1628782211.045100&cid=CAXNXSJHJ)
=> style: [PE-1254] - updates to config view

.github/CODEOWNERS, .github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/question.md, .github/pull_request_template.md
=> chore: add issue/pull request templates and set project codeowners

src/components/Dialog/Dialog.css, src/components/Dialog/Dialog.tsx, src/components/SourceSelect/SourceSelectDropdown.css
This PR adds style updates to the source selection search bar.
- [Jira](https://imgix.atlassian.net/browse/PE-1533)
- [Design](https://www.figma.com/file/g8hMEYgG3KaQ8d3YDVJA4h/Contentful-Plug-In-Designs?node-id=609%3A1663)
=> style: [PE-1533] Updates for source selection search bar

src/components/Dialog/Dialog.tsx, src/components/Gallery/ImageGallery.tsx
=> chore: remove unused props

README.md
=> docs: add a search function section

README.md
=> docs: update README toc

CHANGELOG.md, package-lock.json, package.json
=> chore(release): 1.2.1

package-lock.json, package.json, src/components/ConfigScreen/ConfigScreen.tsx, src/components/Dialog/Dialog.tsx
=> config: add `pluginOrigin` field to every `ImgixAPI` instance

README.md, package.json
Changing Image Manager wording to Asset Manager
Related issue: [e.g. #42]
Code:
```js
// A standalone JS example of what the PR solves
```
=> docs: update Image Manager to Asset Manager

package-lock.json, package.json
These dependencies were included in this project's boilerplate code but were never used.
Merging these changes into `next` first to smoke test before merging into `main`
=> chore(deps): remove nonessential contentful dependencies

src/components/ConfigScreen/ConfigScreen.tsx
=> chore: change instances of "Image Manager" to "Asset Manager" 

README.md, package-lock.json, package.json, src/components/ConfigScreen/ConfigScreen.tsx
=> chore: merge `next` into `main`

CHANGELOG.md, package-lock.json, package.json
=> chore(release): 1.2.3

src/components/Dialog/Dialog.tsx, src/components/SourceSelect/SourceSelectDropdown.css
=> feat: populate the `SourceDropdown` with more sources

package-lock.json, package.json
=> deps: update react-imgix

package-lock.json, package.json, src/components/ActionBar/ActionBar.css, src/components/ActionBar/ActionBar.tsx, src/components/ActionBar/index.ts, src/components/Gallery/ImageGallery.css, src/components/Gallery/ImageGallery.tsx
This PR creates the `ActionBar />` component. This component houses the pagination and "add image" buttons. This component is meant to replace the current footer in the `<ImageGallery />` component.`
Footer had buttons that styling did not match comps.
Footer is now a separate component. It's styling matches the design comps.
- Render more images in the gallery so the footer isn't so far away
- Find a way to make the modal smaller, it's confusing to have the buttons so far away.
- pull down this branch
- run `npm run start`
- open contenful staging and click on "add image"
- select a source
- see the new footer after scrolling
> Footer before
> Footer after
https://user-images.githubusercontent.com/16711614/198703327-fd60792d-7dd9-46bd-92bb-04c9775b77e5.mov
- ~[ ] Update the readme (if …
=> feat: create action bar component

src/components/Dialog/Dialog.css, src/components/Dialog/Dialog.tsx, src/components/UploadButton/UploadButton.css, src/components/UploadButton/UploadButton.tsx
Create `<UploadButton />` component that stores a ref to the upload object in a callback.
No upload button
Upload button exists and stores reference to file in callback function.
https://user-images.githubusercontent.com/16711614/198817748-3f8758fc-6b65-4090-913d-7d12995c7675.mov
- ~[ ] Update the readme (if applicable).~
- ~[ ] Update or add any necessary API documentation (if applicable)~
- ~[ ] Any breaking changes are specified on the commit on which they are introduced with `BREAKING CHANGE` in the body of the commit.~
- ~[ ] If this is a big feature with breaking changes, consider opening an issue to discuss first. This is completely up to you, but please keep in mind that your PR might not be accepted.~
=> feat: create upload button

src/components/SourceSelect/SourceSelectDropdown.css
This PR makes the source select dropdown fit the name of the source
rather than a fixed width. This makes the component easier to use in a
different container.
Source select dropdown had a fixed width
Source select dropdown width matches the source name width
- pull down branch
- run `npm run start`
- open contentful staging env
- click on add image
- see the source select dropdown change size when source is selected
https://user-images.githubusercontent.com/16711614/198852042-1c411810-58c2-462c-83cb-f1b36e9d6d3e.mov
- ~[ ] Update the readme (if applicable).~
- ~[ ] Update or add any necessary API documentation (if applicable)~
- ~[ ] Any breaking changes are specified on the commit on which they are introduced with `BREAKING CHANGE` in the body of the commit.~
- ~[ ] If this is a big …
=> style: set dropdown to fit sourcename length

src/components/Dialog/Dialog.tsx, src/components/UploadButton/UploadButton.tsx
This PR stores the image "blob" as a string that can be set as an `<img>` tag `src` attribute later on.
We were not saving the blob path
We save the blog path
- Pull down branch
- run `npm run start`
- open contentful staging env
- click add image
- click upload
- select a file
- see the console output includes a preview filepath
=> feat(upload): create placeholder image url from file

src/components/Dialog/Dialog.css, src/components/Dialog/Dialog.tsx
This PR uses the management API to upload the selected file to AM. It
first reads the file, transforms it into a base64 encoded buffer, and
then makes a POST request with that buffer.
The request is sent to whatever sourceId, destinationPath, and fileName
the user sets for the file.
https://user-images.githubusercontent.com/16711614/198867184-9c8a128d-62bb-4003-994b-b6f5459e9121.mov
=> feat: upload file to asset mamnager

src/components/Dialog/Dialog.tsx
This PR adds a loading indicator to the upload button.
https://user-images.githubusercontent.com/16711614/198867295-60455f23-b8ba-419d-a3fb-aa47b0b28221.mov
=> feat: show upload indicator when uploading

src/components/UploadButton/UploadButton.tsx
Limit selected files to `/image*` filetypes.
Any filetype could be selected for upload
Only images can be selected for upload
https://user-images.githubusercontent.com/16711614/199100688-6605cac3-59fe-46d1-b845-0f0ddbb727cc.mov
1. Pull down branch, run start, open contenful staging
2. Click add image
3. Select source
4. Click upload
5. Try to select non image asset.
We should probably allow `.gif`, `.pdf`, `.ai` uploads since those are all supported via API v1 AFAIK. Ideally (eventually) `/video*` as well.
=> chore(upload): only accept image files

src/components/Dialog/Dialog.tsx
=> chore: remove stray debugger

.gitignore, cypress.config.ts, cypress/e2e/source-select-spec.cy.ts, cypress/fixtures/example.json, cypress/support/commands.ts, cypress/support/e2e.ts, package-lock.json, package.json, src/index.tsx, tsconfig.json
This PR shims the Contentful SDK when running on a development ENV so that you can render the React application for local development on localhost.
All testing had to run on contentful itself
The app can run on localhost and be tested on cypress
- checkout the branch, run `npm install`
- set the `REACT_APP_CTFL_API_KEY` environment variable to be your API key
- run `npm run start`
- run `npm run cypress` OR, if not testing just go open `http://localhost:3000`
- click on e2e tests
- click to run tests
https://user-images.githubusercontent.com/16711614/200433915-f09dd3c8-09d8-4315-9e42-854c6a6c53ca.mov
=> chore: render app on local host with an sdk shim

src/components/ActionBar/ActionBar.css
=> chore(action-bar): fix z index

src/components/Dialog/Dialog.tsx
This commit adds notifications on upload success or failure. It also correctly handles the error response from the upload API call. Before the call was wrapped in a try-catch and a `.then()` call. The error never made it to the `catch`.`
1. Pull down
2. Run `npm run start`
3. Open contentful staging
4. Click add image
5. Select a source OR Select a source without upload permissions
6. Upload and image
7. See success OR See error
https://user-images.githubusercontent.com/16711614/200992531-25d29c6f-c715-4069-b235-fa1a23ca9522.mov
https://user-images.githubusercontent.com/16711614/200992539-97ad7530-1bbb-40e9-9859-260dec865782.mov
https://user-images.githubusercontent.com/16711614/200992593-8d192f08-5368-4a9d-b83b-f6d1b4dadb09.mov
=> feat: add upload success and error notifications

src/helpers/errors.ts
=> fix: restores search functionality

src/components/Dialog/Dialog.tsx
=> feat: refresh image gallery on upload

src/components/Field/Field.tsx, src/components/Gallery/ImageGallery.css, src/components/Gallery/ImageGallery.tsx
=> fix: ensure action bar stays visible at lower resultions

src/components/Dialog/Dialog.css, src/components/Dialog/Dialog.tsx
This PR adds a destination tooltip to the destination path input field.
No tooltip
Destination tooltip added.
=> feat: add destination tooltip

CHANGELOG.md, package-lock.json, package.json
=> chore(release): 1.2.4

src/components/Dialog/Dialog.css, src/components/Dialog/Dialog.tsx
=> chore: revert remove filename field removal

src/components/ActionBar/ActionBar.css, src/components/Dialog/Dialog.css, src/components/Dialog/Dialog.tsx, src/components/Gallery/GridImage.css, src/components/Gallery/ImageGallery.css, src/components/Icons/Icon.css, src/components/Icons/Icon.tsx
=> style: sync with prettier

src/components/Field/FieldImagePreview.tsx
=> fix: make video field thumbnails 230 by 230 pixels

CHANGELOG.md, package.json
=> chore(release): v1.3.0

CHANGELOG.md, package.json
This PR updates the `CHANGELOG.md` and bumps `package.json` version to release `v.1.4.0` on GitHub and NPM.
This PR also fixes some minor formatting issues from the previous changelog changes.
=> chore(release): v1.4.0

README.md
Some customers don't know what Sources are compatible:
https://imgix.slack.com/archives/CHW1PHD47/p1673282755361489?thread_ts=1673282100.211479&cid=CHW1PHD47
I also don't want to continue updating the README whenever we update a Source, so:
- I specified what is _not_ supported
- I added a link to our documentation
=> docs: adds source compatibility note

README.md, package-lock.json, package.json, src/components/CheckboxList/ParamsCheckboxList.tsx, src/components/Dialog/Dialog.tsx, src/components/Field/Field.css, src/components/Field/Field.spec.tsx, src/components/Field/Field.tsx, src/components/Field/FieldImagePreview.css, src/components/Field/FieldImagePreview.tsx, src/helpers/utils.spec.ts, src/helpers/utils.ts, tsconfig.json
Add per-asset imgix parameter checkboxes so that customers can easily add parameters.
- No params Checkbox
- No filename preview in field
- Params checkbox
- Filename preview in field
https://github.com/imgix/contentful/assets/16711614/56b4c838-e504-48a9-94ad-c003764461b6
1. clone, `npm install`, `npm run test`
2. test out the field using the staging deployment on Contentful
=> feat: add per-asset params checkboxes
