- src/components/ConfigScreen.tsx
Adds the installation workflow needed in order to add an imgix API key to a Contentful application space. 
https://user-images.githubusercontent.com/15919091/111363132-e4d91300-864c-11eb-8f17-9ef41a77f9b3.mov
> feat: allow users to add an API key on the App Config

- README.md
Fixes the license badge on the project README, which was incorrectly pointing to the [Contentful entry](https://www.npmjs.com/package/contentful) on npmjs.com.
> docs: fix license badge

- src/components/Dialog.tsx
- src/components/Field.tsx
This PR adds a dropdown menu in the field dialog populated with all active sources from the account corresponding to the API key provided in #15. It also includes some helper functions for parsing out the image paths, which will later be used to render images from each source.
https://user-images.githubusercontent.com/15919091/113606851-6513e800-95fd-11eb-94b1-154c17c0a200.mov
> feat: create flow for users to select an enabled imgix source

- package-lock.json
- package.json
- src/components/Dialog.spec.tsx
- src/components/Dialog.tsx
- src/components/Gallery.tsx
This PR introduces a new `Gallery` component that is responsible for rendering images based on the Source selected by a user (as seen in #16). This component not only keeps the rendering logic separate from the `Dialog` component but also defers making specific API requests until the Source ID is known. In terms of scope, this PR is mainly concerned with correctly requesting/rendering the images. While the component styling is severely lacking, it will get more attention in a separate PR.
https://user-images.githubusercontent.com/15919091/117900467-16054680-b27e-11eb-8d6d-892d2d5f4d63.mov
> feat: render images via the `Gallery` component

- src/components/Dialog.tsx
- src/components/Gallery.tsx
This PR fixes a bug in which the `Gallery` component was being erroneously rendered although there was no Source selected via the parent `Dialog` component. Conditional rendering of `Gallery` evaluated `this.state.selectedSource` for a truthy value, assuming that the empty state (`{}`) would result in `false`, which it did not (thanks JavaScript). Now, the condition evaluates if a Source ID is selected/defined, which is much more explicit. This PR also makes a performance improvement by preventing repeat requests for the same asset endpoint if the selected Source ID has not changed.
> fix: conditionally render Gallery only if selectedSource.id is defined

- src/components/Dialog.tsx
- src/components/Gallery.tsx
This PR primarily addresses the feedback left in [this comment](https://github.com/imgix/contentful/pull/26#discussion_r635926290). It also takes addresses some other component weirdness related to multiple re-renders by combining multiple calls to `setState`. Finally, it defines a `componentDidMount` hook in the `Gallery` component to handle its first render cycle, while `componentDidUpdate` will handle all subsequent ones. 
Thanks again for the help @frederickfogerty 👍
> fix: don't copy props into state

- package.json
- src/components/Field.tsx
- src/components/Gallery.css
- src/components/Gallery.tsx
This PR displays images in a 3x8 grid format, as opposed to the vertical list they are currently displayed in. The request for this format came from the design team, but may still be subject to change upon further review.
https://user-images.githubusercontent.com/15919091/122844873-6a590880-d2b7-11eb-9ae5-c2fe93a95050.mov
> feat(Galley): display images in a grid

- package-lock.json
- package.json
- src/components/ConfigScreen.tsx
- src/components/Dialog.tsx
- src/components/Field.spec.tsx
- src/components/Field.tsx
- src/components/Gallery.tsx
This PR adds functionality to allow users to select an image (via `onClick` handler), which then saves the image's URL to the parent Field value. This ultimately results in a (stored) image URL that is returned by the Contentful API when requesting the content instance.
https://user-images.githubusercontent.com/15919091/122844966-93799900-d2b7-11eb-8216-6827fcce279d.mov
Note: the specific interaction of "choosing" an image is still subject to change pending feedback from the Design team.
> feat(Field): allow users to select an image via the Dialog

- src/components/ConfigScreen.css
- src/components/ConfigScreen.tsx
This PR is mainly concerned with the following changes:
1) Modifying the `Save` button to now `Verify` a user's API key. More specifically this entails:
1) Executing a request against the API using the current TextField input value
2) Displaying either a success/error notification as a result
3) Displaying a check icon if the latest API key is a valid one
2) Creating an error state when verification is attempted with an empty key
3) Displaying a "loading" button while the verification process is in progress, indicating to users that the action is not yet complete
Successful verification:
https://user-images.githubusercontent.com/15919091/124665483-9fda2600-de61-11eb-88c5-a131a037570b.mov
Unsuccessful verification:
https://user-images.githubusercontent.com/15919091/124665574-ba140400-de61-1 …
> feat(config): add onChange handler to TextField

- src/components/Dialog.css
- src/components/Dialog.tsx
- src/components/Gallery/ImageGallery.tsx
- src/components/Gallery/ImagePlaceholder.css
- src/components/Gallery/ImagePlaceholder.tsx
> This is a stacked PR, please review the linked `diff`
**PR Stack**
| PR 	| Title 	| Merges Into 	|   diff	|
|----	|-------	|-------------	|---	|
|    1	|    refactor: #40  	|        design-updates    	|  [diff](https://github.com/imgix/contentful/pull/40)	|
|    2	|    [ImagePlaceholder](#41)     	|           #40   	|   [diff](https://github.com/imgix/contentful/pull/41/files/2dd79eb..f530cac)	|
This PR removes the placeholder element fro the Gallery component and uses the new ImagePlaceholder component instead. It also removes the placeholder text from the Dialogue component and its corresponding styles, since those are now housed in the ImagePlaceholder.
> feat: create ImagePlaceholder component

- src/components/Dialog.css
- src/components/Dialog.tsx
- src/components/Gallery/ImageGallery.tsx
This PR is mainly concerned with adding the basic UI for pagination and the handler to pass total asset count from the Gallery to the Dialog. All logic for actual pagination will be handled in a different PR.
Note: There is a weird occurrence where the pagination dropdown appears as `Page 1 out of 0` while loading in assets. This will also be addressed in a subsequent PR.
https://user-images.githubusercontent.com/15919091/125686855-c01ead9e-133b-4d98-b59f-44571f16e5b1.mov
> feat(dialog): add buttons to page between Source's images

- src/components/Gallery/GridImage.tsx
- src/components/Gallery/ImageGallery.tsx
- src/components/ImageSelect/ImageSelect.tsx
- src/components/ImageSelect/index.ts
> This is a stacked PR, please review the linked `diff`
**PR Stack**
| PR 	| Title 	| Merges Into 	|   diff	|
|----	|-------	|-------------	|---	|
|    1	|    [hover-styling](https://github.com/imgix/contentful/pull/46)     	|          design-updates  	|   [diff](https://github.com/imgix/contentful/pull/46/files)|
|    2	|    [select-image](https://github.com/imgix/contentful/pull/47)   👈🏼 	|           #46   	|   [diff](https://github.com/imgix/contentful/pull/47/files/6d26f41..81d6612)	|
This PR creates the `ImageSelect` button and uses it inside the `ImageGallery` component to set the currently selected image.
https://user-images.githubusercontent.com/16711614/125832265-03a30bf9-358d-4801-a916-12e3e0159d5c.mov
> feat: add image select button

- src/components/Dialog/Dialog.spec.tsx
- src/components/Dialog/Dialog.tsx
- src/components/Gallery/ImageGallery.tsx
- src/components/Gallery/ImagePagination.tsx
This PR is only concerned with populating the pagination dropdown and setting the handler to (superficially) change the page. In the subsequent PR, the new page index will be passed through the management API to retrieve the new assets. 
Also note that this PR does not style the dropdown list items, which are currently more narrow than the parent element.
https://user-images.githubusercontent.com/15919091/125851152-f4f022a9-4ed0-42f0-8d22-38468b72f09f.mov
> feat: add handler to change the page when an item from the dropdown is selected

- src/components/Gallery/ImagePagination.tsx
This PR adds onClick handlers for paginating forward and back between all available pages for a Source.
It's worth noting that rapidly pressing either button will cause a ratelimit by the API and for the current index and actual displayed page to become out of sync. This edge case will be handled in a subsequent PR which will add onClick debouncing to various parts of the app.
https://user-images.githubusercontent.com/15919091/125866393-0b5da160-0218-4830-8f2e-60903d8c6c5f.mov
> feat(gallery): add `onClick` handlers for paginating forward and back

- src/components/Dialog/Dialog.css
- src/components/Gallery/ImageGallery.tsx
This PR uses the f36 Notification component to display an error dialog when there are no images in a given source. The warning is dismissed when the source is changed and successfully loads images.
This PR also ensures `0` is returned as the image count instead of `NaN` when a source returns no images.
This PR also removes the unused `renderPlaceholder` boolean from the component state.
https://user-images.githubusercontent.com/16711614/125988357-3627c3bf-747e-4e82-980e-6964c18707d0.mov
> feat: show warning and render placeholder when imgix source has no assets

- src/components/Field/Field.spec.tsx
- src/components/Field/Field.tsx
- src/components/Field/FieldImagePreview.css
- src/components/Field/FieldImagePreview.tsx
- src/components/Field/FieldPrompt.tsx
This PR adds two new buttons: `Replace` and `Remove` to the Field component when the field already has a value (image) saved. It also adds styling to format each child component appropriately and resizes the containing iframe depending on which one is being displayed.
https://user-images.githubusercontent.com/15919091/126348867-5a9030db-ffa5-4e44-b594-bf0887724754.mov
> feat(field): allow a selected image to be replaced or removed

- src/components/ConfigScreen/ConfigScreen.css
- src/components/ConfigScreen/ConfigScreen.spec.tsx
- src/components/ConfigScreen/ConfigScreen.tsx
- src/components/Dialog/Dialog.css
- src/components/Field/Field.tsx
- src/components/Gallery/ImagePagination.css
- src/components/Gallery/ImagePagination.tsx
This PR makes adjustments to the App Config copy as per design feedback.
@marco-salcedo, I could use some feedback/thoughts on the following:
- There are two inline `<code>` blocks that could probably use some styling to make them pop out a bit more. Curious if you have any suggestions on what they should specifically be
- With all the new copy added, it looks like the verify Notification is now overlapping with the rest of the page (see video below). I might need your help on realigning it so that they  don't overlap.
https://user-images.githubusercontent.com/15919091/126913988-3c7bd678-f858-4244-8b8f-1409e86d2268.mov
Here is the same page after merging #60 into this branch:
https://user-images.githubusercontent.com/15919091/127205736-a890bc11-c4b4-4136-8261-4ea17c619380.mov
> fix(config): update installation instructions copy; disable `Verify` button if input field is empty

- src/components/Dialog/Dialog.tsx
- src/components/Gallery/ImageGallery.tsx
- src/components/Note/Note.css
- src/components/Note/Note.tsx
- src/components/Note/index.ts
- src/helpers/errors.ts
This PR uses the new `Note.tsx` component and the `errors.ts` helper
to display a warning || error fallback UI whenever an IxError occurs.
To do this, the PR creates an `error` slice of state that gets updated
whenever:
- the API key is invalid
- the account has no sources 
- the source has no images. 
Each displayed `error` is removed from the state so that
only one `error` can ever be displayed at one time (the oldest error).
This PR also adds another slice of state, `verified`, that comes from
values being written to the contentful SDK. This makes it easier to know
whether or not the API key is valid in the `componentDidMount` lifecycle
hook.
The way I'm [currently](https://github.com/imgix/contentful/pull/59#discussion_r675678903) passing URL href and titles to the Note component is a …
> feat: handle API error and warnings in the Dialog component

- src/components/ConfigScreen/ConfigScreen.css
- src/components/ConfigScreen/ConfigScreen.tsx
This PR incorporates some second-round design feedback into the App Config page:
- Selectively change certain `<code>` background colors to help the user more-easily navigate the installation flow
- Minor refactoring of the `<code>` styling
- Moving a portion of the installation instructions into an unordered list, as per request
- Adjusting the `Notification` height offset to account for vertical spacing shift due to the aforementioned changes
https://user-images.githubusercontent.com/15919091/127239386-3996259d-e66f-4f9c-8b01-653063e4471a.mov
> fix(config): change text highlighting to guide user through installation

- src/components/ConfigScreen/ConfigScreen.tsx
- src/components/Dialog/Dialog.tsx
- src/components/Dialog/DialogHeader.tsx
- src/components/Field/Field.tsx
- src/components/Field/FieldImagePreview.css
This PR implements a few changes/fixes based on internal feedback. I will cover each one individually in detail below:
(Temporarily) Remove the `Verify` button's loading spinner
----
There appears to be a bug in forma36's button that causes the loading spinner to show even if the `loading` flag is set to false (details in https://github.com/contentful/forma-36/issues/895). Until this issue is resolved we are going to remove this interaction as it might be confusing for users when attempting to verify their API key.
Reproduction of this issue:
https://user-images.githubusercontent.com/15919091/127609514-7e8b37ea-c7f1-4e46-ac6d-64cbceb33d23.mov
<br><br>
Disable `Verify` button if input field is empty or `undefined`
----
Previously, we only disabled the `Verify` button if the input field …
> fix: implement internal/design feedback

- src/components/ConfigScreen/ConfigScreen.tsx
- src/components/Dialog/Dialog.tsx
- src/components/Note/Note.tsx
- src/components/SourceSelect/SourceSelectDropdown.tsx
- src/helpers/errors.ts
- updates the Error message copy for APIKey and, Source, and Origin errors
- add a `resetNErrors()` function that clears `n` errors from state
- clears the `errors` from the state when a different source is selected
- stores the API key's validity to state any time the application configuration is changed.
- fixes an issue where the Note component was parsing Error messages incorrectly when there was no URL present
> chore: update note copy and store API key validity in state on config change

- package-lock.json
- package.json
- src/components/ConfigScreen/ConfigScreen.tsx
- src/components/Dialog/Dialog.tsx
- src/components/Field/Field.tsx
- src/components/Gallery/ImagePagination.tsx
This PR adds guardrails throughout the intergration (with the help of `lodash.debounce`) to prevent users from accidentally hitting API ratelimits. This can happen when/if a user rapidly presses certain UI elements that are tied to API calls. Because the imgix API has a ratelimit, this can cause some unusual reactions for unaware users. These changes hope to add to the user experience when interacting with this application. See demonstration below:
**Before**
https://user-images.githubusercontent.com/15919091/127715367-ddf232c8-e3ed-480f-9d25-893a4cb76f94.mov
**After**
https://user-images.githubusercontent.com/15919091/127715394-f5c7bcd0-9979-46ff-b62a-d2f9fda681e0.mov
Address feedback left on #35
> fix: debounce any API requests to prevent users from getting ratelimited

- src/components/Field/Field.tsx
This commit introduces a breaking change to how this integration works. Previously, the URL of the selected image was exported as a String via the ctf API. We have since decided that for future flexibility, this value should be exported as a value in a JSON object.
This results in a few (minor) changes in terms of user interactions:
- The integration can only be enabled/used on JSON object fields within a content model, as opposed to short text
- Developers querying the Contentful API for this value will need to query for the `src` key from the resulting response
> feat(field)!: export image src within JSON object

- package-lock.json
- package.json
- src/components/ConfigScreen/ConfigScreen.tsx
This commit rolls back 749fcc3, which temporarily disabled the loading spinner on the Verify button due to a bug. Now that the bug is fixed, we can safely enable it again.
> feat(config): reenable loading spinner

- src/components/ConfigScreen/ConfigScreen.css
- src/components/ConfigScreen/ConfigScreen.spec.tsx
- src/components/ConfigScreen/ConfigScreen.tsx
The intention of this feat is to query the Contentful `spaces` API in order to construct an array of content types with compatible fields (ie `Object`) that users can elect to add the imgix app to. From this, we can surface an interface that allows users to select these fields within the Configuration page.
Once the user has selected any number of fields to install the app to, we then to construct an object in the shape expected by `onConfigure` to persist these choices. For any content type, if there is at least one `enabled` entry then we will create an array of `fieldId` corresponding to the `enabled` (or selected) fields. Once this is returned as `targetState` within `onConfigure`, then the imgix app will be installed in the selected fields.
See demo of this in action: …
> feat: allow users to select fields to add imgix-contentful to

- src/components/ConfigScreen/ConfigScreen.tsx
Addresses the following browser warning `[DOM] Input elements should have autocomplete attributes (suggested: "new-password")`
> fix: add `autoComplete` attribute to API key field

- src/components/Dialog/Dialog.tsx
- src/components/Gallery/ImageGallery.tsx
This PR adds the UI & logic to enable users to be able to search across assets in their selected Source.
In order to implement search, we need the search UI (text input and button) to have access to the same methods where assets are requested and parsed. Unfortunately, there did not appear to be a very react-idiomatic way to handle this situation while also keeping the Dialog and ImageGallery components fully separated.
The proposed solution here is to pull up all asset-related logic to the Dialog level. Once all processing is done, the final asset data (fully-qualified image URLs) can be passed down to ImageGallery as a prop to be rendered.
The search features extends this idea by refactoring the chain of methods used to request and parse assets to accept a query that is ultimately …
> feat: add ability for user to search for assets by `categories`, `keywords`, or `origin_path`

- src/components/Dialog/Dialog.tsx
Because we cannot guarantee that a specific search will return N or more pages, we will reset the current page to the first index (0). This way, if a user is currently viewing page 2, the app will not attempt to show them page 2 of their search when one does not exist.
**General Note about this PR:**
The `Dialog` component will watch for one of two state changes and rerender if either occurs: if a new Source is selected or if a new page of Assets is requested. Because we reset the `currentPageIndex` when executing a search request, this will trigger an extra request for assets in parallel with the search request. Aside from the fact that it's a superfluous request, it will also trigger a ratelimit error from the imgix API.
Although not ideal, the speediest workaround here is to track if a …
> fix: reset currentPageIndex when executing search query

- src/components/Dialog/Dialog.tsx
- src/helpers/errors.ts
This PR displays a specific error Note when a search returns empty results. Part of this implementation requires passing the an error type through the function chain that parses image paths to determine which error to display, either a `noSearchImagesError` or a `noOriginImagesError`.
https://user-images.githubusercontent.com/15919091/141515011-23bbd7ad-71c3-41d4-8c85-1a886e2277cd.mov
> feat: add error type for empty search results

- README.md
- src/components/Dialog/Dialog.tsx
Because the keys of nested JSON fields (e.g. `tags`, `custom_fields`, `colors`) can vary from one object to the next, this can cause brittleness for users who are interfacing with the Contentful API using GraphQL. This is because GraphQL requires users to be explicit about what fields they want to return, rather than being able to query an object for all fields regardless of what they are.
To help with this, some users have suggested [[1](gatsbyjs/gatsby#2490)][[2](https://forums.fauna.com/t/how-to-store-arbitrary-json-object-via-graphql/142/3)] stringifying nested JSON fields and then parsing it clientside. This better ensures that queries won't break even if the returning data's underlying shape somehow breaks. Now each of the following fields will be returned as a string:
- tags
- …
> feat: stringify JSON fields within attributes field 

- README.md
- src/components/Dialog/Dialog.tsx
- src/components/Dialog/index.ts
- src/components/Field/Field.tsx
- src/components/Gallery/ImageGallery.tsx
Previously, the `asset` state variable only tracked an array of strings representing the full URLs of images returned by the user's selected source. Now, `assets` is redefined as an array of objects, including both the aforementioned `src` string and a new key `attributes`. The asset attributes includes all metadata fields returned by the imgix API associated with a given asset, which will be eventually passed through as a new field on the final object returned by Contentful.
> feat: add asset metadata to final returned object

- src/components/Dialog/Dialog.tsx
This PR adds extra guardrails when attempting to access the nested object `dominant_colors`. Optional chaining is added so that in the off chance that `colors` is undefined, the app will still display images in the Gallery.
Fixes #111
> fix: do not access `dominant_colors` if parent object `colors` is undefined

- src/components/ConfigScreen/ConfigScreen.tsx
This PR gives the application better resiliency by not assuming editor interfaces and controls will both exist at the same time. This is because other third-party plugins and/or legacy content types can mutate these fields in unexpected ways.
> fix: optional chain when accessing editor interfaces and controls

- .circleci/config.yml
Update to CircleCI config to support new (18.x onwards) Node versions and unpin Node 17.9.
> ci(node): node compatibility fix

- src/components/Dialog/Dialog.tsx
- src/components/UploadButton/UploadButton.tsx
This PR adds `this.source.attribute.deployment.type` to each source stored in state. It uses this to disable/enable the button for the `selectedSource` when rendering.
Upload was not disabled for `webfolder` sources.
Upload disabled for `webfolder` sources.
https://user-images.githubusercontent.com/16711614/199096135-7e6d1a05-75ef-4bb2-becb-51c54471093d.mov
1. Pull down, run start, open contenful staging
2. Select a webfolder source from the dropdown
3. Try to upload
> feat: disable upload for webfolder source

- src/components/Dialog/Dialog.tsx
The extended drop-down for sources indexes from 1 instead of 0.  As a result, it displays  the second hundred sources.
The extended drop-down for sources indexes from 0, displaying alphabetical sources prior to the second hundred. The source limit has been increased to 200.
> fix: dropdown indexing

- src/components/Dialog/Dialog.css
- src/components/Dialog/Dialog.tsx
- src/components/SourceSelect/SourceSelectDropdown.tsx
This PR disables the upload button after it's clicked. It's disabled as long as `isUploading` in state is `true`. This impedes users from clicking the button many times and trying to upload the same asset over and over.
It also disables the cancel button, source-select dropdown, path field, and filename field while `isUploading` is `true`.
Users could click upload over and over.
The button is disabled after its clicked.
https://user-images.githubusercontent.com/16711614/201010293-8f900da1-186d-4076-96b9-de68351bd1f5.mov
> feat: disable upload button after click

- src/components/Dialog/Dialog.tsx
Webproxy sources were selectable through the source dropdown.
Webproxy sources are no longer visible through the source dropdown.
> chore: filters out webproxy sources

- src/components/ActionBar/ActionBar.tsx
- src/components/ImageSelect/ImageSelect.tsx
Add image button is enabled even when no asset is selected.
Copy has been updated, Add Asset button is disabled when no asset is selected.
> fix: disables add button when no asset selected

- src/components/Dialog/Dialog.tsx
- src/components/Gallery/EmptySourcePlaceholder.tsx
- src/components/Gallery/ImageGallery.tsx
- src/components/Gallery/SourcePlaceholder.tsx
- src/components/Gallery/WebFolderPlaceholder.tsx
- src/components/Gallery/index.ts
- src/components/Note/Note.tsx
- src/helpers/errors.ts
- Adds new error for webfolders with no assets
- Replaces image errors with asset errors to reflect change from Image Manager to Asset Manager
- Errors not resolvable through Contentful are no longer dismissable
- Updates fallback gallery text to reflect source type and situation
Standard source
Web folder
Standard source
Web folder
> chore: update asset errors

- src/components/ActionBar/ActionBar.css
- src/components/Dialog/Dialog.css
- src/components/Dialog/DialogHeader.css
- src/components/Field/Field.tsx
- src/components/Gallery/GridImage.css
- src/components/Gallery/GridImage.tsx
- src/components/Gallery/ImageGallery.css
- src/components/Gallery/ImagePlaceholder.css
- src/components/Note/Note.css
This PR fixes the modal height, upload image preview cropping, filename spacing, and action bar positioning to better match the design comps.
https://user-images.githubusercontent.com/16711614/201764958-9ceee78d-57d6-4b7e-85fb-7555e8c1fd31.mov
> style: address styling feedback

- src/components/Dialog/Dialog.css
- src/components/Dialog/Dialog.tsx
This PR addresses an issue where a non-default font could lead to rendering issues for certain users. It also removes the preview image and filename backgrounds.
- A missing font could lead to font render issues
- Filename input had a background color
- no filename backdrop
- no missing fonts
> style: fix font issues and remove preview background

- src/components/Dialog/Dialog.tsx
Previously, the URL construction logic would use the Source `name` (e.g. `sdk-test` in the screenshot below) to construct the asset URL. This was, however, not ideal as Source names are not always the same as the Source subdomain(s) and therefore, are not guaranteed to conform to the URL spec.
Now, the URL construction logic uses the Source domain, i.e. the first `subdomain` returned by the Sources endpoint, to construct asset URLs.
Create a Source whose name contains spaces (or any other URL-unsafe characters) and link it to an origin with assets. From the Contentful dashboard, request the new Source. 
Before this change, the Dialog renders a blank screen and react-imgix will emit several domain validation errors:
```
Error: Domain must be passed in as fully-qualified domain name and …
```
> fix: construct asset URL using Source `subdomain` instead of `name`

- src/components/Gallery/GridImage.tsx
We leverage the video-generate parameter to use video frames as thumbnails for video assets. We add additional fall-back functionality to use a generic SVG icon for when there's an error rendering the frame.
> feat: display video frame as thumbnail

- src/components/Dialog/Dialog.tsx
Before this commit, webp upload headers were not being removed from the file buffer string, causing incorrect file types on the backend for the image. 
After this commit, webp files upload correctly.
> fix: strip webp upload headers

- src/components/Dialog/Dialog.css
Before this commit, the upload modal's backdrop was scrollable.
After this commit, its position is fixed and cannot be scrolled.
Before
After
> fix: prevent upload modal scrolling

- src/components/Dialog/Dialog.css
Before this commit, the relative, `25%`, left and right positioning would yield inconsistent "centering" results.
After this commit, the content is centered by using left `0` and right `0` positioning and using auto margins.
> style: center upload modal

- src/components/Dialog/Dialog.css
- src/components/Dialog/Dialog.tsx
Before this commit, the upload asset could be renamed before upload. 
After this commit, the upload asset cannot be renamed.
before
after
> refactor: remove filename form field

- src/components/Dialog/Dialog.css
- src/components/Dialog/Dialog.tsx
Before this commit, it was possible to select a web folder source as an upload source in the upload modal's source select dropdown.
After this commit, the webfolder sources are filtered out of the `allSources` slice of state, and therefore not selectable in that dropdown.
> feat: remove webfolder sources from upload sources

- src/components/Field/Field.tsx
- src/components/Field/FieldImagePreview.tsx
Before this commit, un-renderable images were displayed as broken.
After this commit, un-renderable images use the same fallback logic as the `GridImage` component.
before
after
> feat(field-image): use grid-image placeholders

- src/components/Dialog/Dialog.tsx
Before this commit, the error and success toasts were rendered outside the modal in an invisible space. This was because the `offset` value was based off of an AM modal that used to be larger.
After this commit, the `offset` is set to `565` making toasts visible again.
https://user-images.githubusercontent.com/16711614/204858291-9a36316d-2948-4146-a9c6-bb2af2d19d5d.mp4
> fix: decrease toast notifications offset

- src/components/Dialog/Dialog.tsx
- src/components/Gallery/ImageGallery.tsx
This PR addresses two main issues:
- When changing between Sources, the page's `currentIndex` persists between the change. This can cause an issue where the app will try to render a page of assets on a source where that page doesn't exist. Now, we will reset the `currentIndex` to the first page of assets to avoid this issue.
- When changing between Sources, the previously `selectedAsset` persists between the change. This means that a user can select an asset from one source, change their mind, selected a different source, and this be able the add the previously selected asset from the aforementioned source. Now, the `selectedAsset` is reset between different Sources.
https://user-images.githubusercontent.com/15919091/204931593-09316ff2-f79d-42da-8fe0-d2f7fe7dbfd9.mp4 …
> fix: bugs related to state persistence

- README.md
This PR replaces all instances of `image manager` with `asset manager` and many instances of `image` with `asset` in the `README.md.` It also adds a section about the upload capabilities.
https://user-images.githubusercontent.com/16711614/205107815-9d576fd8-530a-41c0-99fa-0e3800b3e896.mp4
> docs: add upload docs

- src/components/SourceSelect/SourceSelectDropdown.tsx
This PR adds a `<Spinner />` to the source select dropdown that renders whenever `allSources.length` is falsy.
https://user-images.githubusercontent.com/16711614/205399840-e03a8120-66bc-442e-a905-e88073f24fcf.mp4
> feat: add loading spinner to source dropdown

- src/components/Gallery/GalleryPlaceholder.tsx
- src/components/Gallery/ImageGallery.tsx
This PR ensures the contentful field is not cleared when a user clicks "cancel" on the modal.
`sdk.close()` would get called without the previously selected asset as an argument, clearing the field.
`sdk.close({...prevAsset})` gets called with the previously selected asset as an argument, preserving the previously value for the field.
https://user-images.githubusercontent.com/16711614/206019039-52ab59f1-fc58-4769-a39e-f110019dfd0d.mp4
> feat: keep previously selected asset populated

- src/components/Dialog/Dialog.tsx
- src/components/Field/Field.tsx
- src/components/Gallery/ImageGallery.tsx
This PR expands on #191, loading previously selected source, to show the previously selected source name in the source dropdown and a loading screen while the sources assets load.
Opening the modal with a pre-selected asset would not show a "loading" placeholder or the pre-selected source, but rather it would show irrelevant placeholder text and a "select source" button.
Opening the modal with a pre-selected asset shows the pre-selected source name in the dropdown and shows a loading screen while the source's assets load
https://user-images.githubusercontent.com/16711614/206080041-d469db7d-1487-4faa-adf1-150acf7f413e.mov
> refactor: show loading on replace

- src/components/Field/Field.tsx
- src/components/Gallery/ImageGallery.tsx
This PR fixes an issue where the `<Field />` was cleared whenever a user clicked away from the modal.
Before this PR, `openCurrentApp` resolved in a way that cleared state when `selectedAsset` was `null` or `undefined`.
After this PR, `openCurrentApp` doesn't call `this.setState()` unless `selectedAsset` evaluates to true.
https://user-images.githubusercontent.com/16711614/206614608-b06613e3-edc3-4820-af5a-b6b5647f9418.mov
> fix: clear on click away

- src/components/Dialog/Dialog.tsx
- src/components/Field/Field.tsx
- src/components/Gallery/ImageGallery.tsx
Fix loading indicator hang on source select change.
Before this commit, sometimes the loading indicator would stick around even though loading was done. This was because we were not checking if the previously selected source and current source ID matched. This meant that, when they did not, we still treated a source select change as an image replacement.
After this commit, the loading indicator goes away on a new source select after the assets have been requested.
https://user-images.githubusercontent.com/16711614/206595085-c62e11e0-ebe1-47f4-afe3-dc83b17ba2c0.mov
> fix: loading indicator when no assets present in source

- README.md
- package-lock.json
- package.json
- src/components/Dialog/Dialog.tsx
- src/components/Gallery/ImageGallery.tsx
- src/helpers/utils.spec.ts
- src/helpers/utils.ts
- Move `stringifyJSONFields` to a helper directory for re-use
- Adds width & height metadata to images on select.
Some images did not have width and height information available once selected.
All images, after selection, will include metadata. Specifically, width and height information.
1. Select an image using the staging deployment of the plugin
2. Make a request for a the Contentful Entry ID of the entry you just edited
3. You should see this is the Contentful API response for the image
```js
"attributes": { 
// … 👇attributes from the `fm=json`request included in the asset.attributes
"media_width": 5773,
"media_height": 8660,
}
```
> feat: add asset metadata on select

- README.md
- src/components/ConfigScreen/ConfigScreen.tsx
- src/components/Dialog/Dialog.tsx
- src/components/Gallery/ImageGallery.tsx
- src/components/SourceSelect/SourceSelectDropdown.tsx
- Adds a configuration field for a default source ID
- Updates sources dropdown button to show loading while fetching sources
- Defaults the Dialog to the configured source ID if set, otherwise fetches sources list
- No way to configure a default source
- Loading indicator on sources dropdown was only shown when clicking dropdown
- Hitting "save" with an invalid configuration would persist the changes despite showing a warning or error
- Customers can configure a default source
- Loading indicator for sources dropdown visible without clicking
- Trying to save an invalid configuration does not persist the changes
Loading indicator
https://github.com/imgix/contentful/assets/16711614/1efa824b-6a0e-4517-b287-2937a350e33b
Default source …
> feat: add default sourceID configuration fields

- src/components/Field/Field.tsx
Updates the Dialog config to allow for scrolling behavior if the contents overflow.
https://github.com/imgix/contentful/assets/16711614/0da46271-58e7-4196-9e88-482cea5f32d8
- `<Dialog>` could not scroll when content overflows from the `<iframe>` parent
https://github.com/imgix/contentful/assets/16711614/6cf779fb-f75a-478e-bc66-860e8cf9d354
- `<Dialog>` can be scrolled when the dimensions are larger than the iframe parent
- x ] If this is a big feature with breaking changes, consider opening an issue to discuss first. This is completely up to you, but please keep in mind that your PR might not be accepted.
> feat: allow scrolling on content overflow in smaller viewports

- package-lock.json
- package.json
- src/components/Gallery/ImageGallery.tsx
- src/helpers/utils.ts
- Ensures that we don't stringify values that are already strings when storing the asset data
- Catches fetch errors when `fm=json` is not supported
> fix: dont stringify values that are already strings
